let perj = require('./perj')
let parent = perj.create({ name: 'parent' })
parent.info('parent log message')
let child1 = parent.child({ name: 'child1' })
child1.info('child1 log message')
let child2 = child1.child({ name: 'child2' })
child2.info('child2 log message')
let child3 = child2.child({ name: 'child3' })
child3.info('child3 log message')
let child4 = child3.child({ name: 'child4' })
child4.info('child4 log message')
